use_frameworks!
target 'CMDFramework_Tests' do
  pod 'CMDFramework', :path => '../'
  pod 'EasyPeasy'
  pod 'libPhoneNumber-iOS'
  pod 'Restofire'
  pod 'SDWebImage'
  pod 'SSZipArchive'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'PKHUD'
  pod 'EasyAnimation'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'LGSideMenuController'
  pod 'DateToolsSwift'
  pod 'DKImagePickerController'
end
