use_frameworks!
target 'CMDFramework_Tests' do
  pod 'CMDFramework', :path => '../'
  pod 'EasyPeasy'
  pod 'libPhoneNumber-iOS'
  pod 'Restofire'
  pod 'SDWebImage'
  pod 'SSZipArchive'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'PKHUD'
  pod 'EasyAnimation'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'LGSideMenuController'
  pod 'DateToolsSwift'
  pod 'DKImagePickerController'
  pod 'ActiveLabel'

  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '3.0'
          end
      end
  end
  
end
